// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: schrodinger_contract_impl.proto
// </auto-generated>
// Original file comments:
// the version of the language, use proto3 for contracts
#pragma warning disable 0414, 1591
#region Designer generated code

using System.Collections.Generic;
using aelf = global::AElf.CSharp.Core;

namespace Schrodinger {

  #region Events
  public partial class RewardConfigSet : aelf::IEvent<RewardConfigSet>
  {
    public global::System.Collections.Generic.IEnumerable<RewardConfigSet> GetIndexed()
    {
      return new List<RewardConfigSet>
      {
      };
    }

    public RewardConfigSet GetNonIndexed()
    {
      return new RewardConfigSet
      {
        Tick = Tick,
        List = List,
        Pool = Pool,
      };
    }
  }

  public partial class Spun : aelf::IEvent<Spun>
  {
    public global::System.Collections.Generic.IEnumerable<Spun> GetIndexed()
    {
      return new List<Spun>
      {
      };
    }

    public Spun GetNonIndexed()
    {
      return new Spun
      {
        Tick = Tick,
        SpinInfo = SpinInfo,
        Seed = Seed,
      };
    }
  }

  public partial class AdoptedWithVoucher : aelf::IEvent<AdoptedWithVoucher>
  {
    public global::System.Collections.Generic.IEnumerable<AdoptedWithVoucher> GetIndexed()
    {
      return new List<AdoptedWithVoucher>
      {
      };
    }

    public AdoptedWithVoucher GetNonIndexed()
    {
      return new AdoptedWithVoucher
      {
        VoucherInfo = VoucherInfo,
      };
    }
  }

  public partial class VoucherConfirmed : aelf::IEvent<VoucherConfirmed>
  {
    public global::System.Collections.Generic.IEnumerable<VoucherConfirmed> GetIndexed()
    {
      return new List<VoucherConfirmed>
      {
      };
    }

    public VoucherConfirmed GetNonIndexed()
    {
      return new VoucherConfirmed
      {
        VoucherInfo = VoucherInfo,
      };
    }
  }

  public partial class VoucherAirdropped : aelf::IEvent<VoucherAirdropped>
  {
    public global::System.Collections.Generic.IEnumerable<VoucherAirdropped> GetIndexed()
    {
      return new List<VoucherAirdropped>
      {
      };
    }

    public VoucherAirdropped GetNonIndexed()
    {
      return new VoucherAirdropped
      {
        Tick = Tick,
        List = List,
        Amount = Amount,
      };
    }
  }

  public partial class AirdropControllerAdded : aelf::IEvent<AirdropControllerAdded>
  {
    public global::System.Collections.Generic.IEnumerable<AirdropControllerAdded> GetIndexed()
    {
      return new List<AirdropControllerAdded>
      {
      };
    }

    public AirdropControllerAdded GetNonIndexed()
    {
      return new AirdropControllerAdded
      {
        Tick = Tick,
        Addresses = Addresses,
      };
    }
  }

  public partial class AirdropControllerRemoved : aelf::IEvent<AirdropControllerRemoved>
  {
    public global::System.Collections.Generic.IEnumerable<AirdropControllerRemoved> GetIndexed()
    {
      return new List<AirdropControllerRemoved>
      {
      };
    }

    public AirdropControllerRemoved GetNonIndexed()
    {
      return new AirdropControllerRemoved
      {
        Tick = Tick,
        Addresses = Addresses,
      };
    }
  }

  public partial class RerollConfigSet : aelf::IEvent<RerollConfigSet>
  {
    public global::System.Collections.Generic.IEnumerable<RerollConfigSet> GetIndexed()
    {
      return new List<RerollConfigSet>
      {
      };
    }

    public RerollConfigSet GetNonIndexed()
    {
      return new RerollConfigSet
      {
        Tick = Tick,
        Config = Config,
      };
    }
  }

  public partial class MergeRatesConfigSet : aelf::IEvent<MergeRatesConfigSet>
  {
    public global::System.Collections.Generic.IEnumerable<MergeRatesConfigSet> GetIndexed()
    {
      return new List<MergeRatesConfigSet>
      {
      };
    }

    public MergeRatesConfigSet GetNonIndexed()
    {
      return new MergeRatesConfigSet
      {
        Tick = Tick,
        MergeRates = MergeRates,
        MaximumLevel = MaximumLevel,
      };
    }
  }

  public partial class MergeConfigSet : aelf::IEvent<MergeConfigSet>
  {
    public global::System.Collections.Generic.IEnumerable<MergeConfigSet> GetIndexed()
    {
      return new List<MergeConfigSet>
      {
      };
    }

    public MergeConfigSet GetNonIndexed()
    {
      return new MergeConfigSet
      {
        Tick = Tick,
        Config = Config,
      };
    }
  }

  public partial class Merged : aelf::IEvent<Merged>
  {
    public global::System.Collections.Generic.IEnumerable<Merged> GetIndexed()
    {
      return new List<Merged>
      {
      };
    }

    public Merged GetNonIndexed()
    {
      return new Merged
      {
        Tick = Tick,
        AdoptIdA = AdoptIdA,
        AdoptIdB = AdoptIdB,
        SymbolA = SymbolA,
        SymbolB = SymbolB,
        AmountA = AmountA,
        AmountB = AmountB,
        AdoptInfo = AdoptInfo,
        LossAmount = LossAmount,
        CommissionAmount = CommissionAmount,
      };
    }
  }

  public partial class VoucherAdoptionConfigSet : aelf::IEvent<VoucherAdoptionConfigSet>
  {
    public global::System.Collections.Generic.IEnumerable<VoucherAdoptionConfigSet> GetIndexed()
    {
      return new List<VoucherAdoptionConfigSet>
      {
      };
    }

    public VoucherAdoptionConfigSet GetNonIndexed()
    {
      return new VoucherAdoptionConfigSet
      {
        Tick = Tick,
        Config = Config,
      };
    }
  }

  #endregion
  public static partial class SchrodingerContractImplContainer
  {
    static readonly string __ServiceName = "SchrodingerContractImpl";

    #region Marshallers
    static readonly aelf::Marshaller<global::Schrodinger.InitializeInput> __Marshaller_InitializeInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.InitializeInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.DeployInput> __Marshaller_DeployInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.DeployInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.ConfirmInput> __Marshaller_ConfirmInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.ConfirmInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.RerollInput> __Marshaller_RerollInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.RerollInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.AdoptMaxGenInput> __Marshaller_AdoptMaxGenInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.AdoptMaxGenInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.Hash> __Marshaller_aelf_Hash = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.Hash.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.SetAttributeInput> __Marshaller_SetAttributeInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.SetAttributeInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.SetAttributesPerGenInput> __Marshaller_SetAttributesPerGenInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.SetAttributesPerGenInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.SetMaxGenerationInput> __Marshaller_SetMaxGenerationInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.SetMaxGenerationInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.SetRatesInput> __Marshaller_SetRatesInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.SetRatesInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.SetRecipientInput> __Marshaller_SetRecipientInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.SetRecipientInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.SetImageCountInput> __Marshaller_SetImageCountInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.SetImageCountInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.SetInscriptionAdminInput> __Marshaller_SetInscriptionAdminInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.SetInscriptionAdminInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.SetCrossGenerationConfigInput> __Marshaller_SetCrossGenerationConfigInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.SetCrossGenerationConfigInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.SetSignatoryInput> __Marshaller_SetSignatoryInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.SetSignatoryInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.StringValue> __Marshaller_google_protobuf_StringValue = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.StringValue.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.Address> __Marshaller_aelf_Address = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.Address.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.InscriptionInfo> __Marshaller_InscriptionInfo = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.InscriptionInfo.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.AttributeInfos> __Marshaller_AttributeInfos = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.AttributeInfos.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.GetAttributeValuesInput> __Marshaller_GetAttributeValuesInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.GetAttributeValuesInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.AdoptInfo> __Marshaller_AdoptInfo = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.AdoptInfo.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.GetTokenInfoOutput> __Marshaller_GetTokenInfoOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.GetTokenInfoOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Int64Value> __Marshaller_google_protobuf_Int64Value = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Int64Value.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.Config> __Marshaller_Config = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.Config.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Int32Value> __Marshaller_google_protobuf_Int32Value = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Int32Value.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.SetAttributeConfigInput> __Marshaller_SetAttributeConfigInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.SetAttributeConfigInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.SetPointsProportionListInput> __Marshaller_SetPointsProportionListInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.SetPointsProportionListInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.BatchSettleInput> __Marshaller_BatchSettleInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.BatchSettleInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.JoinInput> __Marshaller_JoinInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.JoinInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.AcceptReferralInput> __Marshaller_AcceptReferralInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.AcceptReferralInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.BoolValue> __Marshaller_google_protobuf_BoolValue = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.BoolValue.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.TransferFromReceivingAddressInput> __Marshaller_TransferFromReceivingAddressInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.TransferFromReceivingAddressInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.SetOfficialDomainAliasInput> __Marshaller_SetOfficialDomainAliasInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.SetOfficialDomainAliasInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.SetRewardConfigInput> __Marshaller_SetRewardConfigInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.SetRewardConfigInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.GetRewardConfigOutput> __Marshaller_GetRewardConfigOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.GetRewardConfigOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.SpinInput> __Marshaller_SpinInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.SpinInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.SpinInfo> __Marshaller_SpinInfo = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.SpinInfo.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.AdoptWithVoucherInput> __Marshaller_AdoptWithVoucherInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.AdoptWithVoucherInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.VoucherInfo> __Marshaller_VoucherInfo = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.VoucherInfo.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.ConfirmVoucherInput> __Marshaller_ConfirmVoucherInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.ConfirmVoucherInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.GetAdoptionVoucherAmountInput> __Marshaller_GetAdoptionVoucherAmountInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.GetAdoptionVoucherAmountInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.SetVoucherAdoptionConfigInput> __Marshaller_SetVoucherAdoptionConfigInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.SetVoucherAdoptionConfigInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.VoucherAdoptionConfig> __Marshaller_VoucherAdoptionConfig = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.VoucherAdoptionConfig.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.AirdropVoucherInput> __Marshaller_AirdropVoucherInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.AirdropVoucherInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.AddressList> __Marshaller_AddressList = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.AddressList.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.AddAirdropControllerInput> __Marshaller_AddAirdropControllerInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.AddAirdropControllerInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.RemoveAirdropControllerInput> __Marshaller_RemoveAirdropControllerInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.RemoveAirdropControllerInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.SetRerollConfigInput> __Marshaller_SetRerollConfigInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.SetRerollConfigInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.RerollConfig> __Marshaller_RerollConfig = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.RerollConfig.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.SetMergeConfigInput> __Marshaller_SetMergeConfigInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.SetMergeConfigInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.GetMergeConfigOutput> __Marshaller_GetMergeConfigOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.GetMergeConfigOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.SetMergeRatesConfigInput> __Marshaller_SetMergeRatesConfigInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.SetMergeRatesConfigInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.MergeInput> __Marshaller_MergeInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.MergeInput.Parser.ParseFrom);
    #endregion

    #region Methods
    static readonly aelf::Method<global::Schrodinger.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Initialize = new aelf::Method<global::Schrodinger.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Initialize",
        __Marshaller_InitializeInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.DeployInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Deploy = new aelf::Method<global::Schrodinger.DeployInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Deploy",
        __Marshaller_DeployInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.ConfirmInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Confirm = new aelf::Method<global::Schrodinger.ConfirmInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Confirm",
        __Marshaller_ConfirmInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.RerollInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Reroll = new aelf::Method<global::Schrodinger.RerollInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Reroll",
        __Marshaller_RerollInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.AdoptMaxGenInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AdoptMaxGen = new aelf::Method<global::Schrodinger.AdoptMaxGenInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AdoptMaxGen",
        __Marshaller_AdoptMaxGenInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Hash, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RerollAdoption = new aelf::Method<global::AElf.Types.Hash, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RerollAdoption",
        __Marshaller_aelf_Hash,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.SetAttributeInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetFixedAttribute = new aelf::Method<global::Schrodinger.SetAttributeInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetFixedAttribute",
        __Marshaller_SetAttributeInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.SetAttributeInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetRandomAttribute = new aelf::Method<global::Schrodinger.SetAttributeInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetRandomAttribute",
        __Marshaller_SetAttributeInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.SetAttributesPerGenInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetAttributesPerGen = new aelf::Method<global::Schrodinger.SetAttributesPerGenInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetAttributesPerGen",
        __Marshaller_SetAttributesPerGenInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.SetMaxGenerationInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetMaxGeneration = new aelf::Method<global::Schrodinger.SetMaxGenerationInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetMaxGeneration",
        __Marshaller_SetMaxGenerationInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.SetRatesInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetRates = new aelf::Method<global::Schrodinger.SetRatesInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetRates",
        __Marshaller_SetRatesInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.SetRecipientInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetRecipient = new aelf::Method<global::Schrodinger.SetRecipientInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetRecipient",
        __Marshaller_SetRecipientInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.SetImageCountInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetImageCount = new aelf::Method<global::Schrodinger.SetImageCountInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetImageCount",
        __Marshaller_SetImageCountInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.SetInscriptionAdminInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetInscriptionAdmin = new aelf::Method<global::Schrodinger.SetInscriptionAdminInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetInscriptionAdmin",
        __Marshaller_SetInscriptionAdminInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.SetCrossGenerationConfigInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetCrossGenerationConfig = new aelf::Method<global::Schrodinger.SetCrossGenerationConfigInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetCrossGenerationConfig",
        __Marshaller_SetCrossGenerationConfigInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.SetSignatoryInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetSignatory = new aelf::Method<global::Schrodinger.SetSignatoryInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetSignatory",
        __Marshaller_SetSignatoryInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::AElf.Types.Address> __Method_GetSignatory = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetSignatory",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Schrodinger.InscriptionInfo> __Method_GetInscriptionInfo = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Schrodinger.InscriptionInfo>(
        aelf::MethodType.View,
        __ServiceName,
        "GetInscriptionInfo",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_InscriptionInfo);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Google.Protobuf.WellKnownTypes.StringValue> __Method_GetTick = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Google.Protobuf.WellKnownTypes.StringValue>(
        aelf::MethodType.View,
        __ServiceName,
        "GetTick",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_google_protobuf_StringValue);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Google.Protobuf.WellKnownTypes.StringValue> __Method_GetParent = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Google.Protobuf.WellKnownTypes.StringValue>(
        aelf::MethodType.View,
        __ServiceName,
        "GetParent",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_google_protobuf_StringValue);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Schrodinger.AttributeInfos> __Method_GetAttributeTypes = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Schrodinger.AttributeInfos>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAttributeTypes",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_AttributeInfos);

    static readonly aelf::Method<global::Schrodinger.GetAttributeValuesInput, global::Schrodinger.AttributeInfos> __Method_GetAttributeValues = new aelf::Method<global::Schrodinger.GetAttributeValuesInput, global::Schrodinger.AttributeInfos>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAttributeValues",
        __Marshaller_GetAttributeValuesInput,
        __Marshaller_AttributeInfos);

    static readonly aelf::Method<global::AElf.Types.Hash, global::Schrodinger.AdoptInfo> __Method_GetAdoptInfo = new aelf::Method<global::AElf.Types.Hash, global::Schrodinger.AdoptInfo>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAdoptInfo",
        __Marshaller_aelf_Hash,
        __Marshaller_AdoptInfo);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Schrodinger.GetTokenInfoOutput> __Method_GetTokenInfo = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Schrodinger.GetTokenInfoOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetTokenInfo",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_GetTokenInfoOutput);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetSymbolCount = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetSymbolCount",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Schrodinger.Config, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetConfig = new aelf::Method<global::Schrodinger.Config, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetConfig",
        __Marshaller_Config,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetAdmin = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetAdmin",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address> __Method_GetAdmin = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAdmin",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetMaxGenerationConfig = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetMaxGenerationConfig",
        __Marshaller_google_protobuf_Int32Value,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetImageMaxSize = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetImageMaxSize",
        __Marshaller_google_protobuf_Int64Value,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetImageMaxCount = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetImageMaxCount",
        __Marshaller_google_protobuf_Int64Value,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.SetAttributeConfigInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetAttributeConfig = new aelf::Method<global::Schrodinger.SetAttributeConfigInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetAttributeConfig",
        __Marshaller_SetAttributeConfigInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Schrodinger.Config> __Method_GetConfig = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Schrodinger.Config>(
        aelf::MethodType.View,
        __ServiceName,
        "GetConfig",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_Config);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetImageUriMaxSize = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetImageUriMaxSize",
        __Marshaller_google_protobuf_Int64Value,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetImageUriMaxSize = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetImageUriMaxSize",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::AElf.Types.Hash, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetPointsContractDAppId = new aelf::Method<global::AElf.Types.Hash, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetPointsContractDAppId",
        __Marshaller_aelf_Hash,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetPointsContract = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetPointsContract",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.SetPointsProportionListInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetPointsProportionList = new aelf::Method<global::Schrodinger.SetPointsProportionListInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetPointsProportionList",
        __Marshaller_SetPointsProportionListInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetPointsSettleAdmin = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetPointsSettleAdmin",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.BatchSettleInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_BatchSettle = new aelf::Method<global::Schrodinger.BatchSettleInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "BatchSettle",
        __Marshaller_BatchSettleInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.JoinInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Join = new aelf::Method<global::Schrodinger.JoinInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Join",
        __Marshaller_JoinInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.AcceptReferralInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AcceptReferral = new aelf::Method<global::Schrodinger.AcceptReferralInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AcceptReferral",
        __Marshaller_AcceptReferralInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Hash> __Method_GetPointsContractDAppId = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Hash>(
        aelf::MethodType.View,
        __ServiceName,
        "GetPointsContractDAppId",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_Hash);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address> __Method_GetPointsContract = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetPointsContract",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.BoolValue> __Method_GetJoinRecord = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.BoolValue>(
        aelf::MethodType.View,
        __ServiceName,
        "GetJoinRecord",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_BoolValue);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetPointsProportion = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetPointsProportion",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address> __Method_GetPointsSettleAdmin = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetPointsSettleAdmin",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::Schrodinger.TransferFromReceivingAddressInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_TransferFromReceivingAddress = new aelf::Method<global::Schrodinger.TransferFromReceivingAddressInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "TransferFromReceivingAddress",
        __Marshaller_TransferFromReceivingAddressInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::AElf.Types.Address> __Method_GetReceivingAddress = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetReceivingAddress",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::Schrodinger.SetOfficialDomainAliasInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetOfficialDomainAlias = new aelf::Method<global::Schrodinger.SetOfficialDomainAliasInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetOfficialDomainAlias",
        __Marshaller_SetOfficialDomainAliasInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.StringValue> __Method_GetOfficialDomainAlias = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.StringValue>(
        aelf::MethodType.View,
        __ServiceName,
        "GetOfficialDomainAlias",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_StringValue);

    static readonly aelf::Method<global::Schrodinger.SetRewardConfigInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetRewardConfig = new aelf::Method<global::Schrodinger.SetRewardConfigInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetRewardConfig",
        __Marshaller_SetRewardConfigInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Schrodinger.GetRewardConfigOutput> __Method_GetRewardConfig = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Schrodinger.GetRewardConfigOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetRewardConfig",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_GetRewardConfigOutput);

    static readonly aelf::Method<global::Schrodinger.SpinInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Spin = new aelf::Method<global::Schrodinger.SpinInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Spin",
        __Marshaller_SpinInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Hash, global::Schrodinger.SpinInfo> __Method_GetSpinInfo = new aelf::Method<global::AElf.Types.Hash, global::Schrodinger.SpinInfo>(
        aelf::MethodType.View,
        __ServiceName,
        "GetSpinInfo",
        __Marshaller_aelf_Hash,
        __Marshaller_SpinInfo);

    static readonly aelf::Method<global::Schrodinger.AdoptWithVoucherInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AdoptWithVoucher = new aelf::Method<global::Schrodinger.AdoptWithVoucherInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AdoptWithVoucher",
        __Marshaller_AdoptWithVoucherInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Hash, global::Schrodinger.VoucherInfo> __Method_GetVoucherInfo = new aelf::Method<global::AElf.Types.Hash, global::Schrodinger.VoucherInfo>(
        aelf::MethodType.View,
        __ServiceName,
        "GetVoucherInfo",
        __Marshaller_aelf_Hash,
        __Marshaller_VoucherInfo);

    static readonly aelf::Method<global::Schrodinger.ConfirmVoucherInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ConfirmVoucher = new aelf::Method<global::Schrodinger.ConfirmVoucherInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ConfirmVoucher",
        __Marshaller_ConfirmVoucherInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.GetAdoptionVoucherAmountInput, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetAdoptionVoucherAmount = new aelf::Method<global::Schrodinger.GetAdoptionVoucherAmountInput, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAdoptionVoucherAmount",
        __Marshaller_GetAdoptionVoucherAmountInput,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Schrodinger.SetVoucherAdoptionConfigInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetVoucherAdoptionConfig = new aelf::Method<global::Schrodinger.SetVoucherAdoptionConfigInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetVoucherAdoptionConfig",
        __Marshaller_SetVoucherAdoptionConfigInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Schrodinger.VoucherAdoptionConfig> __Method_GetVoucherAdoptionConfig = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Schrodinger.VoucherAdoptionConfig>(
        aelf::MethodType.View,
        __ServiceName,
        "GetVoucherAdoptionConfig",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_VoucherAdoptionConfig);

    static readonly aelf::Method<global::Schrodinger.AirdropVoucherInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AirdropVoucher = new aelf::Method<global::Schrodinger.AirdropVoucherInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AirdropVoucher",
        __Marshaller_AirdropVoucherInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Schrodinger.AddressList> __Method_GetAirdropController = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Schrodinger.AddressList>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAirdropController",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_AddressList);

    static readonly aelf::Method<global::Schrodinger.AddAirdropControllerInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AddAirdropController = new aelf::Method<global::Schrodinger.AddAirdropControllerInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AddAirdropController",
        __Marshaller_AddAirdropControllerInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.RemoveAirdropControllerInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveAirdropController = new aelf::Method<global::Schrodinger.RemoveAirdropControllerInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RemoveAirdropController",
        __Marshaller_RemoveAirdropControllerInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.SetRerollConfigInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetRerollConfig = new aelf::Method<global::Schrodinger.SetRerollConfigInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetRerollConfig",
        __Marshaller_SetRerollConfigInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Schrodinger.RerollConfig> __Method_GetRerollConfig = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Schrodinger.RerollConfig>(
        aelf::MethodType.View,
        __ServiceName,
        "GetRerollConfig",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_RerollConfig);

    static readonly aelf::Method<global::Schrodinger.SetMergeConfigInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetMergeConfig = new aelf::Method<global::Schrodinger.SetMergeConfigInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetMergeConfig",
        __Marshaller_SetMergeConfigInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Schrodinger.GetMergeConfigOutput> __Method_GetMergeConfig = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Schrodinger.GetMergeConfigOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetMergeConfig",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_GetMergeConfigOutput);

    static readonly aelf::Method<global::Schrodinger.SetMergeRatesConfigInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetMergeRatesConfig = new aelf::Method<global::Schrodinger.SetMergeRatesConfigInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetMergeRatesConfig",
        __Marshaller_SetMergeRatesConfigInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.MergeInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Merge = new aelf::Method<global::Schrodinger.MergeInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Merge",
        __Marshaller_MergeInput,
        __Marshaller_google_protobuf_Empty);

    #endregion

    #region Descriptors
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Schrodinger.SchrodingerContractImplReflection.Descriptor.Services[0]; }
    }

    public static global::System.Collections.Generic.IReadOnlyList<global::Google.Protobuf.Reflection.ServiceDescriptor> Descriptors
    {
      get
      {
        return new global::System.Collections.Generic.List<global::Google.Protobuf.Reflection.ServiceDescriptor>()
        {
          global::AElf.Standards.ACS12.Acs12Reflection.Descriptor.Services[0],
          global::Schrodinger.SchrodingerContractReflection.Descriptor.Services[0],
          global::Schrodinger.SchrodingerContractImplReflection.Descriptor.Services[0],
        };
      }
    }
    #endregion

    /// <summary>Base class for the contract of SchrodingerContractImpl</summary>
  }
}
#endregion

