// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: schrodinger_contract.proto
// </auto-generated>
// Original file comments:
// the version of the language, use proto3 for contracts
#pragma warning disable 0414, 1591
#region Designer generated code

using System.Collections.Generic;
using aelf = global::AElf.CSharp.Core;

namespace Schrodinger {

  #region Events
  public partial class Joined : aelf::IEvent<Joined>
  {
    public global::System.Collections.Generic.IEnumerable<Joined> GetIndexed()
    {
      return new List<Joined>
      {
      };
    }

    public Joined GetNonIndexed()
    {
      return new Joined
      {
        Domain = Domain,
        Registrant = Registrant,
      };
    }
  }

  public partial class Deployed : aelf::IEvent<Deployed>
  {
    public global::System.Collections.Generic.IEnumerable<Deployed> GetIndexed()
    {
      return new List<Deployed>
      {
      };
    }

    public Deployed GetNonIndexed()
    {
      return new Deployed
      {
        Tick = Tick,
        Ancestor = Ancestor,
        MaxGeneration = MaxGeneration,
        TotalSupply = TotalSupply,
        Decimals = Decimals,
        AttributeLists = AttributeLists,
        ImageCount = ImageCount,
        Issuer = Issuer,
        Owner = Owner,
        IssueChainId = IssueChainId,
        ExternalInfos = ExternalInfos,
        TokenName = TokenName,
        Deployer = Deployer,
        CrossGenerationConfig = CrossGenerationConfig,
        IsWeightEnabled = IsWeightEnabled,
        Admin = Admin,
        LossRate = LossRate,
        CommissionRate = CommissionRate,
        AttributesPerGen = AttributesPerGen,
        Signatory = Signatory,
        ImageUri = ImageUri,
        MaxGenLossRate = MaxGenLossRate,
      };
    }
  }

  public partial class Adopted : aelf::IEvent<Adopted>
  {
    public global::System.Collections.Generic.IEnumerable<Adopted> GetIndexed()
    {
      return new List<Adopted>
      {
      };
    }

    public Adopted GetNonIndexed()
    {
      return new Adopted
      {
        AdoptId = AdoptId,
        Parent = Parent,
        ParentGen = ParentGen,
        InputAmount = InputAmount,
        LossAmount = LossAmount,
        CommissionAmount = CommissionAmount,
        OutputAmount = OutputAmount,
        ImageCount = ImageCount,
        Adopter = Adopter,
        BlockHeight = BlockHeight,
        Attributes = Attributes,
        Gen = Gen,
        Ancestor = Ancestor,
        Symbol = Symbol,
        TokenName = TokenName,
      };
    }
  }

  public partial class Confirmed : aelf::IEvent<Confirmed>
  {
    public global::System.Collections.Generic.IEnumerable<Confirmed> GetIndexed()
    {
      return new List<Confirmed>
      {
      };
    }

    public Confirmed GetNonIndexed()
    {
      return new Confirmed
      {
        AdoptId = AdoptId,
        Parent = Parent,
        Symbol = Symbol,
        TotalSupply = TotalSupply,
        Decimals = Decimals,
        Gen = Gen,
        Attributes = Attributes,
        Issuer = Issuer,
        Owner = Owner,
        IssueChainId = IssueChainId,
        ExternalInfos = ExternalInfos,
        TokenName = TokenName,
        Deployer = Deployer,
        ImageUri = ImageUri,
      };
    }
  }

  public partial class Rerolled : aelf::IEvent<Rerolled>
  {
    public global::System.Collections.Generic.IEnumerable<Rerolled> GetIndexed()
    {
      return new List<Rerolled>
      {
      };
    }

    public Rerolled GetNonIndexed()
    {
      return new Rerolled
      {
        Symbol = Symbol,
        Ancestor = Ancestor,
        Amount = Amount,
        Recipient = Recipient,
      };
    }
  }

  public partial class FixedAttributeSet : aelf::IEvent<FixedAttributeSet>
  {
    public global::System.Collections.Generic.IEnumerable<FixedAttributeSet> GetIndexed()
    {
      return new List<FixedAttributeSet>
      {
      };
    }

    public FixedAttributeSet GetNonIndexed()
    {
      return new FixedAttributeSet
      {
        Tick = Tick,
        RemovedAttribute = RemovedAttribute,
        AddedAttribute = AddedAttribute,
      };
    }
  }

  public partial class RandomAttributeSet : aelf::IEvent<RandomAttributeSet>
  {
    public global::System.Collections.Generic.IEnumerable<RandomAttributeSet> GetIndexed()
    {
      return new List<RandomAttributeSet>
      {
      };
    }

    public RandomAttributeSet GetNonIndexed()
    {
      return new RandomAttributeSet
      {
        Tick = Tick,
        RemovedAttribute = RemovedAttribute,
        AddedAttribute = AddedAttribute,
      };
    }
  }

  public partial class AttributesPerGenerationSet : aelf::IEvent<AttributesPerGenerationSet>
  {
    public global::System.Collections.Generic.IEnumerable<AttributesPerGenerationSet> GetIndexed()
    {
      return new List<AttributesPerGenerationSet>
      {
      };
    }

    public AttributesPerGenerationSet GetNonIndexed()
    {
      return new AttributesPerGenerationSet
      {
        Tick = Tick,
        AttributesPerGen = AttributesPerGen,
      };
    }
  }

  public partial class ImageCountSet : aelf::IEvent<ImageCountSet>
  {
    public global::System.Collections.Generic.IEnumerable<ImageCountSet> GetIndexed()
    {
      return new List<ImageCountSet>
      {
      };
    }

    public ImageCountSet GetNonIndexed()
    {
      return new ImageCountSet
      {
        Tick = Tick,
        ImageCount = ImageCount,
      };
    }
  }

  public partial class MaxGenerationSet : aelf::IEvent<MaxGenerationSet>
  {
    public global::System.Collections.Generic.IEnumerable<MaxGenerationSet> GetIndexed()
    {
      return new List<MaxGenerationSet>
      {
      };
    }

    public MaxGenerationSet GetNonIndexed()
    {
      return new MaxGenerationSet
      {
        Tick = Tick,
        Gen = Gen,
      };
    }
  }

  public partial class RatesSet : aelf::IEvent<RatesSet>
  {
    public global::System.Collections.Generic.IEnumerable<RatesSet> GetIndexed()
    {
      return new List<RatesSet>
      {
      };
    }

    public RatesSet GetNonIndexed()
    {
      return new RatesSet
      {
        Tick = Tick,
        LossRate = LossRate,
        CommissionRate = CommissionRate,
        MaxGenLossRate = MaxGenLossRate,
      };
    }
  }

  public partial class RecipientSet : aelf::IEvent<RecipientSet>
  {
    public global::System.Collections.Generic.IEnumerable<RecipientSet> GetIndexed()
    {
      return new List<RecipientSet>
      {
      };
    }

    public RecipientSet GetNonIndexed()
    {
      return new RecipientSet
      {
        Tick = Tick,
        Recipient = Recipient,
      };
    }
  }

  public partial class InscriptionAdminSet : aelf::IEvent<InscriptionAdminSet>
  {
    public global::System.Collections.Generic.IEnumerable<InscriptionAdminSet> GetIndexed()
    {
      return new List<InscriptionAdminSet>
      {
      };
    }

    public InscriptionAdminSet GetNonIndexed()
    {
      return new InscriptionAdminSet
      {
        Tick = Tick,
        Admin = Admin,
      };
    }
  }

  public partial class CrossGenerationConfigSet : aelf::IEvent<CrossGenerationConfigSet>
  {
    public global::System.Collections.Generic.IEnumerable<CrossGenerationConfigSet> GetIndexed()
    {
      return new List<CrossGenerationConfigSet>
      {
      };
    }

    public CrossGenerationConfigSet GetNonIndexed()
    {
      return new CrossGenerationConfigSet
      {
        Tick = Tick,
        CrossGenerationConfig = CrossGenerationConfig,
      };
    }
  }

  public partial class ConfigSet : aelf::IEvent<ConfigSet>
  {
    public global::System.Collections.Generic.IEnumerable<ConfigSet> GetIndexed()
    {
      return new List<ConfigSet>
      {
      };
    }

    public ConfigSet GetNonIndexed()
    {
      return new ConfigSet
      {
        Config = Config,
      };
    }
  }

  public partial class MaxGenerationConfigSet : aelf::IEvent<MaxGenerationConfigSet>
  {
    public global::System.Collections.Generic.IEnumerable<MaxGenerationConfigSet> GetIndexed()
    {
      return new List<MaxGenerationConfigSet>
      {
      };
    }

    public MaxGenerationConfigSet GetNonIndexed()
    {
      return new MaxGenerationConfigSet
      {
        MaxGen = MaxGen,
      };
    }
  }

  public partial class ImageMaxSizeSet : aelf::IEvent<ImageMaxSizeSet>
  {
    public global::System.Collections.Generic.IEnumerable<ImageMaxSizeSet> GetIndexed()
    {
      return new List<ImageMaxSizeSet>
      {
      };
    }

    public ImageMaxSizeSet GetNonIndexed()
    {
      return new ImageMaxSizeSet
      {
        ImageMaxSize = ImageMaxSize,
      };
    }
  }

  public partial class ImageMaxCountSet : aelf::IEvent<ImageMaxCountSet>
  {
    public global::System.Collections.Generic.IEnumerable<ImageMaxCountSet> GetIndexed()
    {
      return new List<ImageMaxCountSet>
      {
      };
    }

    public ImageMaxCountSet GetNonIndexed()
    {
      return new ImageMaxCountSet
      {
        ImageMaxCount = ImageMaxCount,
      };
    }
  }

  public partial class AttributeConfigSet : aelf::IEvent<AttributeConfigSet>
  {
    public global::System.Collections.Generic.IEnumerable<AttributeConfigSet> GetIndexed()
    {
      return new List<AttributeConfigSet>
      {
      };
    }

    public AttributeConfigSet GetNonIndexed()
    {
      return new AttributeConfigSet
      {
        TraitTypeMaxCount = TraitTypeMaxCount,
        TraitValueMaxCount = TraitValueMaxCount,
        AttributeMaxLength = AttributeMaxLength,
        MaxAttributesPerGen = MaxAttributesPerGen,
        FixedTraitTypeMaxCount = FixedTraitTypeMaxCount,
      };
    }
  }

  public partial class AdminSet : aelf::IEvent<AdminSet>
  {
    public global::System.Collections.Generic.IEnumerable<AdminSet> GetIndexed()
    {
      return new List<AdminSet>
      {
      };
    }

    public AdminSet GetNonIndexed()
    {
      return new AdminSet
      {
        Admin = Admin,
      };
    }
  }

  public partial class SignatorySet : aelf::IEvent<SignatorySet>
  {
    public global::System.Collections.Generic.IEnumerable<SignatorySet> GetIndexed()
    {
      return new List<SignatorySet>
      {
      };
    }

    public SignatorySet GetNonIndexed()
    {
      return new SignatorySet
      {
        Tick = Tick,
        Signatory = Signatory,
      };
    }
  }

  public partial class ImageUriMaxSizeSet : aelf::IEvent<ImageUriMaxSizeSet>
  {
    public global::System.Collections.Generic.IEnumerable<ImageUriMaxSizeSet> GetIndexed()
    {
      return new List<ImageUriMaxSizeSet>
      {
      };
    }

    public ImageUriMaxSizeSet GetNonIndexed()
    {
      return new ImageUriMaxSizeSet
      {
        ImageUriMaxSize = ImageUriMaxSize,
      };
    }
  }

  public partial class ReferralAccepted : aelf::IEvent<ReferralAccepted>
  {
    public global::System.Collections.Generic.IEnumerable<ReferralAccepted> GetIndexed()
    {
      return new List<ReferralAccepted>
      {
      };
    }

    public ReferralAccepted GetNonIndexed()
    {
      return new ReferralAccepted
      {
        Referrer = Referrer,
        Invitee = Invitee,
      };
    }
  }

  public partial class OfficialDomainAliasSet : aelf::IEvent<OfficialDomainAliasSet>
  {
    public global::System.Collections.Generic.IEnumerable<OfficialDomainAliasSet> GetIndexed()
    {
      return new List<OfficialDomainAliasSet>
      {
      };
    }

    public OfficialDomainAliasSet GetNonIndexed()
    {
      return new OfficialDomainAliasSet
      {
        Alias = Alias,
      };
    }
  }

  public partial class AdoptionRerolled : aelf::IEvent<AdoptionRerolled>
  {
    public global::System.Collections.Generic.IEnumerable<AdoptionRerolled> GetIndexed()
    {
      return new List<AdoptionRerolled>
      {
      };
    }

    public AdoptionRerolled GetNonIndexed()
    {
      return new AdoptionRerolled
      {
        AdoptId = AdoptId,
        Symbol = Symbol,
        Amount = Amount,
        Account = Account,
      };
    }
  }

  public partial class AdoptionUpdated : aelf::IEvent<AdoptionUpdated>
  {
    public global::System.Collections.Generic.IEnumerable<AdoptionUpdated> GetIndexed()
    {
      return new List<AdoptionUpdated>
      {
      };
    }

    public AdoptionUpdated GetNonIndexed()
    {
      return new AdoptionUpdated
      {
        AdoptId = AdoptId,
        Parent = Parent,
        ParentGen = ParentGen,
        InputAmount = InputAmount,
        LossAmount = LossAmount,
        CommissionAmount = CommissionAmount,
        OutputAmount = OutputAmount,
        ImageCount = ImageCount,
        Adopter = Adopter,
        BlockHeight = BlockHeight,
        Attributes = Attributes,
        Gen = Gen,
        Ancestor = Ancestor,
        Symbol = Symbol,
        TokenName = TokenName,
      };
    }
  }

  public partial class RewardConfigSet : aelf::IEvent<RewardConfigSet>
  {
    public global::System.Collections.Generic.IEnumerable<RewardConfigSet> GetIndexed()
    {
      return new List<RewardConfigSet>
      {
      };
    }

    public RewardConfigSet GetNonIndexed()
    {
      return new RewardConfigSet
      {
        Tick = Tick,
        List = List,
        Pool = Pool,
      };
    }
  }

  public partial class Spun : aelf::IEvent<Spun>
  {
    public global::System.Collections.Generic.IEnumerable<Spun> GetIndexed()
    {
      return new List<Spun>
      {
      };
    }

    public Spun GetNonIndexed()
    {
      return new Spun
      {
        Tick = Tick,
        SpinInfo = SpinInfo,
        Seed = Seed,
      };
    }
  }

  public partial class AdoptedWithVoucher : aelf::IEvent<AdoptedWithVoucher>
  {
    public global::System.Collections.Generic.IEnumerable<AdoptedWithVoucher> GetIndexed()
    {
      return new List<AdoptedWithVoucher>
      {
      };
    }

    public AdoptedWithVoucher GetNonIndexed()
    {
      return new AdoptedWithVoucher
      {
        VoucherInfo = VoucherInfo,
      };
    }
  }

  public partial class VoucherConfirmed : aelf::IEvent<VoucherConfirmed>
  {
    public global::System.Collections.Generic.IEnumerable<VoucherConfirmed> GetIndexed()
    {
      return new List<VoucherConfirmed>
      {
      };
    }

    public VoucherConfirmed GetNonIndexed()
    {
      return new VoucherConfirmed
      {
        VoucherInfo = VoucherInfo,
      };
    }
  }

  public partial class VoucherAirdropped : aelf::IEvent<VoucherAirdropped>
  {
    public global::System.Collections.Generic.IEnumerable<VoucherAirdropped> GetIndexed()
    {
      return new List<VoucherAirdropped>
      {
      };
    }

    public VoucherAirdropped GetNonIndexed()
    {
      return new VoucherAirdropped
      {
        Tick = Tick,
        List = List,
        Amount = Amount,
      };
    }
  }

  public partial class AirdropAdminSet : aelf::IEvent<AirdropAdminSet>
  {
    public global::System.Collections.Generic.IEnumerable<AirdropAdminSet> GetIndexed()
    {
      return new List<AirdropAdminSet>
      {
      };
    }

    public AirdropAdminSet GetNonIndexed()
    {
      return new AirdropAdminSet
      {
        Tick = Tick,
        Admin = Admin,
      };
    }
  }

  #endregion
  public static partial class SchrodingerContractContainer
  {
    static readonly string __ServiceName = "SchrodingerContract";

    #region Marshallers
    static readonly aelf::Marshaller<global::Schrodinger.InitializeInput> __Marshaller_InitializeInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.InitializeInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.DeployInput> __Marshaller_DeployInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.DeployInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.AdoptInput> __Marshaller_AdoptInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.AdoptInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.ConfirmInput> __Marshaller_ConfirmInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.ConfirmInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.RerollInput> __Marshaller_RerollInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.RerollInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.AdoptMaxGenInput> __Marshaller_AdoptMaxGenInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.AdoptMaxGenInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.Hash> __Marshaller_aelf_Hash = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.Hash.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.SetAttributeInput> __Marshaller_SetAttributeInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.SetAttributeInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.SetAttributesPerGenInput> __Marshaller_SetAttributesPerGenInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.SetAttributesPerGenInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.SetMaxGenerationInput> __Marshaller_SetMaxGenerationInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.SetMaxGenerationInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.SetRatesInput> __Marshaller_SetRatesInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.SetRatesInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.SetRecipientInput> __Marshaller_SetRecipientInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.SetRecipientInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.SetImageCountInput> __Marshaller_SetImageCountInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.SetImageCountInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.SetInscriptionAdminInput> __Marshaller_SetInscriptionAdminInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.SetInscriptionAdminInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.SetCrossGenerationConfigInput> __Marshaller_SetCrossGenerationConfigInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.SetCrossGenerationConfigInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.SetSignatoryInput> __Marshaller_SetSignatoryInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.SetSignatoryInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.StringValue> __Marshaller_google_protobuf_StringValue = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.StringValue.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.Address> __Marshaller_aelf_Address = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.Address.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.InscriptionInfo> __Marshaller_InscriptionInfo = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.InscriptionInfo.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.AttributeInfos> __Marshaller_AttributeInfos = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.AttributeInfos.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.GetAttributeValuesInput> __Marshaller_GetAttributeValuesInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.GetAttributeValuesInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.AdoptInfo> __Marshaller_AdoptInfo = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.AdoptInfo.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.GetTokenInfoOutput> __Marshaller_GetTokenInfoOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.GetTokenInfoOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.Config> __Marshaller_Config = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.Config.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Int32Value> __Marshaller_google_protobuf_Int32Value = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Int32Value.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Int64Value> __Marshaller_google_protobuf_Int64Value = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Int64Value.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.SetAttributeConfigInput> __Marshaller_SetAttributeConfigInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.SetAttributeConfigInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.SetPointsProportionListInput> __Marshaller_SetPointsProportionListInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.SetPointsProportionListInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.BatchSettleInput> __Marshaller_BatchSettleInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.BatchSettleInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.JoinInput> __Marshaller_JoinInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.JoinInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.AcceptReferralInput> __Marshaller_AcceptReferralInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.AcceptReferralInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.BoolValue> __Marshaller_google_protobuf_BoolValue = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.BoolValue.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.TransferFromReceivingAddressInput> __Marshaller_TransferFromReceivingAddressInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.TransferFromReceivingAddressInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.SetOfficialDomainAliasInput> __Marshaller_SetOfficialDomainAliasInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.SetOfficialDomainAliasInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.SetRewardConfigInput> __Marshaller_SetRewardConfigInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.SetRewardConfigInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.GetRewardConfigOutput> __Marshaller_GetRewardConfigOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.GetRewardConfigOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.SpinInput> __Marshaller_SpinInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.SpinInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.SpinInfo> __Marshaller_SpinInfo = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.SpinInfo.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.AdoptWithVoucherInput> __Marshaller_AdoptWithVoucherInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.AdoptWithVoucherInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.VoucherInfo> __Marshaller_VoucherInfo = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.VoucherInfo.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.ConfirmVoucherInput> __Marshaller_ConfirmVoucherInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.ConfirmVoucherInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.GetAdoptionVoucherAmountInput> __Marshaller_GetAdoptionVoucherAmountInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.GetAdoptionVoucherAmountInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.AirdropVoucherInput> __Marshaller_AirdropVoucherInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.AirdropVoucherInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Schrodinger.SetAirdropAdminInput> __Marshaller_SetAirdropAdminInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schrodinger.SetAirdropAdminInput.Parser.ParseFrom);
    #endregion

    #region Methods
    static readonly aelf::Method<global::Schrodinger.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Initialize = new aelf::Method<global::Schrodinger.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Initialize",
        __Marshaller_InitializeInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.DeployInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Deploy = new aelf::Method<global::Schrodinger.DeployInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Deploy",
        __Marshaller_DeployInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.AdoptInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Adopt = new aelf::Method<global::Schrodinger.AdoptInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Adopt",
        __Marshaller_AdoptInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.ConfirmInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Confirm = new aelf::Method<global::Schrodinger.ConfirmInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Confirm",
        __Marshaller_ConfirmInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.RerollInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Reroll = new aelf::Method<global::Schrodinger.RerollInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Reroll",
        __Marshaller_RerollInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.AdoptMaxGenInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AdoptMaxGen = new aelf::Method<global::Schrodinger.AdoptMaxGenInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AdoptMaxGen",
        __Marshaller_AdoptMaxGenInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Hash, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RerollAdoption = new aelf::Method<global::AElf.Types.Hash, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RerollAdoption",
        __Marshaller_aelf_Hash,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Hash, global::Google.Protobuf.WellKnownTypes.Empty> __Method_UpdateAdoption = new aelf::Method<global::AElf.Types.Hash, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "UpdateAdoption",
        __Marshaller_aelf_Hash,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.SetAttributeInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetFixedAttribute = new aelf::Method<global::Schrodinger.SetAttributeInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetFixedAttribute",
        __Marshaller_SetAttributeInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.SetAttributeInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetRandomAttribute = new aelf::Method<global::Schrodinger.SetAttributeInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetRandomAttribute",
        __Marshaller_SetAttributeInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.SetAttributesPerGenInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetAttributesPerGen = new aelf::Method<global::Schrodinger.SetAttributesPerGenInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetAttributesPerGen",
        __Marshaller_SetAttributesPerGenInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.SetMaxGenerationInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetMaxGeneration = new aelf::Method<global::Schrodinger.SetMaxGenerationInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetMaxGeneration",
        __Marshaller_SetMaxGenerationInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.SetRatesInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetRates = new aelf::Method<global::Schrodinger.SetRatesInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetRates",
        __Marshaller_SetRatesInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.SetRecipientInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetRecipient = new aelf::Method<global::Schrodinger.SetRecipientInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetRecipient",
        __Marshaller_SetRecipientInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.SetImageCountInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetImageCount = new aelf::Method<global::Schrodinger.SetImageCountInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetImageCount",
        __Marshaller_SetImageCountInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.SetInscriptionAdminInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetInscriptionAdmin = new aelf::Method<global::Schrodinger.SetInscriptionAdminInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetInscriptionAdmin",
        __Marshaller_SetInscriptionAdminInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.SetCrossGenerationConfigInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetCrossGenerationConfig = new aelf::Method<global::Schrodinger.SetCrossGenerationConfigInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetCrossGenerationConfig",
        __Marshaller_SetCrossGenerationConfigInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.SetSignatoryInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetSignatory = new aelf::Method<global::Schrodinger.SetSignatoryInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetSignatory",
        __Marshaller_SetSignatoryInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::AElf.Types.Address> __Method_GetSignatory = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetSignatory",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Schrodinger.InscriptionInfo> __Method_GetInscriptionInfo = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Schrodinger.InscriptionInfo>(
        aelf::MethodType.View,
        __ServiceName,
        "GetInscriptionInfo",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_InscriptionInfo);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Google.Protobuf.WellKnownTypes.StringValue> __Method_GetTick = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Google.Protobuf.WellKnownTypes.StringValue>(
        aelf::MethodType.View,
        __ServiceName,
        "GetTick",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_google_protobuf_StringValue);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Google.Protobuf.WellKnownTypes.StringValue> __Method_GetParent = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Google.Protobuf.WellKnownTypes.StringValue>(
        aelf::MethodType.View,
        __ServiceName,
        "GetParent",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_google_protobuf_StringValue);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Schrodinger.AttributeInfos> __Method_GetAttributeTypes = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Schrodinger.AttributeInfos>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAttributeTypes",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_AttributeInfos);

    static readonly aelf::Method<global::Schrodinger.GetAttributeValuesInput, global::Schrodinger.AttributeInfos> __Method_GetAttributeValues = new aelf::Method<global::Schrodinger.GetAttributeValuesInput, global::Schrodinger.AttributeInfos>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAttributeValues",
        __Marshaller_GetAttributeValuesInput,
        __Marshaller_AttributeInfos);

    static readonly aelf::Method<global::AElf.Types.Hash, global::Schrodinger.AdoptInfo> __Method_GetAdoptInfo = new aelf::Method<global::AElf.Types.Hash, global::Schrodinger.AdoptInfo>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAdoptInfo",
        __Marshaller_aelf_Hash,
        __Marshaller_AdoptInfo);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Schrodinger.GetTokenInfoOutput> __Method_GetTokenInfo = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Schrodinger.GetTokenInfoOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetTokenInfo",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_GetTokenInfoOutput);

    static readonly aelf::Method<global::Schrodinger.Config, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetConfig = new aelf::Method<global::Schrodinger.Config, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetConfig",
        __Marshaller_Config,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetAdmin = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetAdmin",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address> __Method_GetAdmin = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAdmin",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetMaxGenerationConfig = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetMaxGenerationConfig",
        __Marshaller_google_protobuf_Int32Value,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetImageMaxSize = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetImageMaxSize",
        __Marshaller_google_protobuf_Int64Value,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetImageMaxCount = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetImageMaxCount",
        __Marshaller_google_protobuf_Int64Value,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.SetAttributeConfigInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetAttributeConfig = new aelf::Method<global::Schrodinger.SetAttributeConfigInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetAttributeConfig",
        __Marshaller_SetAttributeConfigInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Schrodinger.Config> __Method_GetConfig = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Schrodinger.Config>(
        aelf::MethodType.View,
        __ServiceName,
        "GetConfig",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_Config);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetImageUriMaxSize = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetImageUriMaxSize",
        __Marshaller_google_protobuf_Int64Value,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetImageUriMaxSize = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetImageUriMaxSize",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::AElf.Types.Hash, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetPointsContractDAppId = new aelf::Method<global::AElf.Types.Hash, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetPointsContractDAppId",
        __Marshaller_aelf_Hash,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetPointsContract = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetPointsContract",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.SetPointsProportionListInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetPointsProportionList = new aelf::Method<global::Schrodinger.SetPointsProportionListInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetPointsProportionList",
        __Marshaller_SetPointsProportionListInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetPointsSettleAdmin = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetPointsSettleAdmin",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.BatchSettleInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_BatchSettle = new aelf::Method<global::Schrodinger.BatchSettleInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "BatchSettle",
        __Marshaller_BatchSettleInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.JoinInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Join = new aelf::Method<global::Schrodinger.JoinInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Join",
        __Marshaller_JoinInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.AcceptReferralInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AcceptReferral = new aelf::Method<global::Schrodinger.AcceptReferralInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AcceptReferral",
        __Marshaller_AcceptReferralInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Hash> __Method_GetPointsContractDAppId = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Hash>(
        aelf::MethodType.View,
        __ServiceName,
        "GetPointsContractDAppId",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_Hash);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address> __Method_GetPointsContract = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetPointsContract",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.BoolValue> __Method_GetJoinRecord = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.BoolValue>(
        aelf::MethodType.View,
        __ServiceName,
        "GetJoinRecord",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_BoolValue);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetPointsProportion = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetPointsProportion",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address> __Method_GetPointsSettleAdmin = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetPointsSettleAdmin",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::Schrodinger.TransferFromReceivingAddressInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_TransferFromReceivingAddress = new aelf::Method<global::Schrodinger.TransferFromReceivingAddressInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "TransferFromReceivingAddress",
        __Marshaller_TransferFromReceivingAddressInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::AElf.Types.Address> __Method_GetReceivingAddress = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetReceivingAddress",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::Schrodinger.SetOfficialDomainAliasInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetOfficialDomainAlias = new aelf::Method<global::Schrodinger.SetOfficialDomainAliasInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetOfficialDomainAlias",
        __Marshaller_SetOfficialDomainAliasInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.StringValue> __Method_GetOfficialDomainAlias = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.StringValue>(
        aelf::MethodType.View,
        __ServiceName,
        "GetOfficialDomainAlias",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_StringValue);

    static readonly aelf::Method<global::Schrodinger.SetRewardConfigInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetRewardConfig = new aelf::Method<global::Schrodinger.SetRewardConfigInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetRewardConfig",
        __Marshaller_SetRewardConfigInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Schrodinger.GetRewardConfigOutput> __Method_GetRewardConfig = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Schrodinger.GetRewardConfigOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetRewardConfig",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_GetRewardConfigOutput);

    static readonly aelf::Method<global::Schrodinger.SpinInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Spin = new aelf::Method<global::Schrodinger.SpinInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Spin",
        __Marshaller_SpinInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Hash, global::Schrodinger.SpinInfo> __Method_GetSpinInfo = new aelf::Method<global::AElf.Types.Hash, global::Schrodinger.SpinInfo>(
        aelf::MethodType.View,
        __ServiceName,
        "GetSpinInfo",
        __Marshaller_aelf_Hash,
        __Marshaller_SpinInfo);

    static readonly aelf::Method<global::Schrodinger.AdoptWithVoucherInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AdoptWithVoucher = new aelf::Method<global::Schrodinger.AdoptWithVoucherInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AdoptWithVoucher",
        __Marshaller_AdoptWithVoucherInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Hash, global::Schrodinger.VoucherInfo> __Method_GetVoucherInfo = new aelf::Method<global::AElf.Types.Hash, global::Schrodinger.VoucherInfo>(
        aelf::MethodType.View,
        __ServiceName,
        "GetVoucherInfo",
        __Marshaller_aelf_Hash,
        __Marshaller_VoucherInfo);

    static readonly aelf::Method<global::Schrodinger.ConfirmVoucherInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ConfirmVoucher = new aelf::Method<global::Schrodinger.ConfirmVoucherInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ConfirmVoucher",
        __Marshaller_ConfirmVoucherInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.GetAdoptionVoucherAmountInput, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetAdoptionVoucherAmount = new aelf::Method<global::Schrodinger.GetAdoptionVoucherAmountInput, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAdoptionVoucherAmount",
        __Marshaller_GetAdoptionVoucherAmountInput,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Schrodinger.AirdropVoucherInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AirdropVoucher = new aelf::Method<global::Schrodinger.AirdropVoucherInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AirdropVoucher",
        __Marshaller_AirdropVoucherInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Schrodinger.SetAirdropAdminInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetAirdropAdmin = new aelf::Method<global::Schrodinger.SetAirdropAdminInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetAirdropAdmin",
        __Marshaller_SetAirdropAdminInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::AElf.Types.Address> __Method_GetAirdropAdmin = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAirdropAdmin",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_aelf_Address);

    #endregion

    #region Descriptors
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Schrodinger.SchrodingerContractReflection.Descriptor.Services[0]; }
    }

    public static global::System.Collections.Generic.IReadOnlyList<global::Google.Protobuf.Reflection.ServiceDescriptor> Descriptors
    {
      get
      {
        return new global::System.Collections.Generic.List<global::Google.Protobuf.Reflection.ServiceDescriptor>()
        {
          global::AElf.Standards.ACS12.Acs12Reflection.Descriptor.Services[0],
          global::Schrodinger.SchrodingerContractReflection.Descriptor.Services[0],
        };
      }
    }
    #endregion

  }
}
#endregion

