// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: schrodinger_contract_main.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SchrodingerMain {

  /// <summary>Holder for reflection information generated from schrodinger_contract_main.proto</summary>
  public static partial class SchrodingerContractMainReflection {

    #region Descriptor
    /// <summary>File descriptor for schrodinger_contract_main.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SchrodingerContractMainReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9zY2hyb2Rpbmdlcl9jb250cmFjdF9tYWluLnByb3RvGg9hZWxmL2NvcmUu",
            "cHJvdG8aEmFlbGYvb3B0aW9ucy5wcm90bxoLYWNzMTIucHJvdG8aG2dvb2ds",
            "ZS9wcm90b2J1Zi9lbXB0eS5wcm90bxofZ29vZ2xlL3Byb3RvYnVmL3RpbWVz",
            "dGFtcC5wcm90byJ8Cg9Jbml0aWFsaXplSW5wdXQSHAoFYWRtaW4YASABKAsy",
            "DS5hZWxmLkFkZHJlc3MSFgoOaW1hZ2VfbWF4X3NpemUYAiABKAMSMwocc2No",
            "cm9kaW5nZXJfY29udHJhY3RfYWRkcmVzcxgDIAEoCzINLmFlbGYuQWRkcmVz",
            "cyKQAQoLRGVwbG95SW5wdXQSDAoEdGljaxgBIAEoCRINCgVpbWFnZRgCIAEo",
            "CRITCgtzZWVkX3N5bWJvbBgDIAEoCRISCgp0b2tlbl9uYW1lGAQgASgJEhAK",
            "CGRlY2ltYWxzGAUgASgFEhYKDmlzc3VlX2NoYWluX2lkGAYgASgFEhEKCWlt",
            "YWdlX3VyaRgHIAEoCSJnCg1FeHRlcm5hbEluZm9zEigKBXZhbHVlGAEgAygL",
            "MhkuRXh0ZXJuYWxJbmZvcy5WYWx1ZUVudHJ5GiwKClZhbHVlRW50cnkSCwoD",
            "a2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASJWChVEZXBsb3lJbnNjcmlw",
            "dGlvbkluZm8SCQoBcBgBIAEoCRIKCgJvcBgCIAEoCRIMCgR0aWNrGAMgASgJ",
            "EgsKA21heBgEIAEoCRILCgNsaW0YBSABKAkiogIKEkNvbGxlY3Rpb25EZXBs",
            "b3llZBIOCgZzeW1ib2wYASABKAkSFAoMdG90YWxfc3VwcGx5GAIgASgDEh0K",
            "Bmlzc3VlchgDIAEoCzINLmFlbGYuQWRkcmVzcxIcCgVvd25lchgEIAEoCzIN",
            "LmFlbGYuQWRkcmVzcxIWCg5pc3N1ZV9jaGFpbl9pZBgFIAEoBRIxChljb2xs",
            "ZWN0aW9uX2V4dGVybmFsX2luZm9zGAYgASgLMg4uRXh0ZXJuYWxJbmZvcxIf",
            "CghkZXBsb3llchgHIAEoCzINLmFlbGYuQWRkcmVzcxISCgp0b2tlbl9uYW1l",
            "GAggASgJEhAKCGRlY2ltYWxzGAkgASgFEhEKCWltYWdlX3VyaRgKIAEoCToE",
            "oLsYATLqBAoXU2Nocm9kaW5nZXJNYWluQ29udHJhY3QSOAoKSW5pdGlhbGl6",
            "ZRIQLkluaXRpYWxpemVJbnB1dBoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eSIA",
            "EjAKBkRlcGxveRIMLkRlcGxveUlucHV0GhYuZ29vZ2xlLnByb3RvYnVmLkVt",
            "cHR5IgASSAoPU2V0SW1hZ2VNYXhTaXplEhsuZ29vZ2xlLnByb3RvYnVmLklu",
            "dDY0VmFsdWUaFi5nb29nbGUucHJvdG9idWYuRW1wdHkiABJNCg9HZXRJbWFn",
            "ZU1heFNpemUSFi5nb29nbGUucHJvdG9idWYuRW1wdHkaGy5nb29nbGUucHJv",
            "dG9idWYuSW50NjRWYWx1ZSIFiIn3AQESMwoIU2V0QWRtaW4SDS5hZWxmLkFk",
            "ZHJlc3MaFi5nb29nbGUucHJvdG9idWYuRW1wdHkiABI4CghHZXRBZG1pbhIW",
            "Lmdvb2dsZS5wcm90b2J1Zi5FbXB0eRoNLmFlbGYuQWRkcmVzcyIFiIn3AQES",
            "SAodU2V0U2Nocm9kaW5nZXJDb250cmFjdEFkZHJlc3MSDS5hZWxmLkFkZHJl",
            "c3MaFi5nb29nbGUucHJvdG9idWYuRW1wdHkiABJNCh1HZXRTY2hyb2Rpbmdl",
            "ckNvbnRyYWN0QWRkcmVzcxIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRoNLmFl",
            "bGYuQWRkcmVzcyIFiIn3AQEaQsrK9gELYWNzMTIucHJvdG+yzPYBLVNjaHJv",
            "ZGluZ2VyLk1haW4uU2Nocm9kaW5nZXJNYWluQ29udHJhY3RTdGF0ZUISqgIP",
            "U2Nocm9kaW5nZXJNYWluYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::AElf.Types.CoreReflection.Descriptor, global::AElf.OptionsReflection.Descriptor, global::AElf.Standards.ACS12.Acs12Reflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SchrodingerMain.InitializeInput), global::SchrodingerMain.InitializeInput.Parser, new[]{ "Admin", "ImageMaxSize", "SchrodingerContractAddress" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SchrodingerMain.DeployInput), global::SchrodingerMain.DeployInput.Parser, new[]{ "Tick", "Image", "SeedSymbol", "TokenName", "Decimals", "IssueChainId", "ImageUri" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SchrodingerMain.ExternalInfos), global::SchrodingerMain.ExternalInfos.Parser, new[]{ "Value" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::SchrodingerMain.DeployInscriptionInfo), global::SchrodingerMain.DeployInscriptionInfo.Parser, new[]{ "P", "Op", "Tick", "Max", "Lim" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SchrodingerMain.CollectionDeployed), global::SchrodingerMain.CollectionDeployed.Parser, new[]{ "Symbol", "TotalSupply", "Issuer", "Owner", "IssueChainId", "CollectionExternalInfos", "Deployer", "TokenName", "Decimals", "ImageUri" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class InitializeInput : pb::IMessage<InitializeInput>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<InitializeInput> _parser = new pb::MessageParser<InitializeInput>(() => new InitializeInput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<InitializeInput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SchrodingerMain.SchrodingerContractMainReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InitializeInput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InitializeInput(InitializeInput other) : this() {
      admin_ = other.admin_ != null ? other.admin_.Clone() : null;
      imageMaxSize_ = other.imageMaxSize_;
      schrodingerContractAddress_ = other.schrodingerContractAddress_ != null ? other.schrodingerContractAddress_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InitializeInput Clone() {
      return new InitializeInput(this);
    }

    /// <summary>Field number for the "admin" field.</summary>
    public const int AdminFieldNumber = 1;
    private global::AElf.Types.Address admin_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AElf.Types.Address Admin {
      get { return admin_; }
      set {
        admin_ = value;
      }
    }

    /// <summary>Field number for the "image_max_size" field.</summary>
    public const int ImageMaxSizeFieldNumber = 2;
    private long imageMaxSize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ImageMaxSize {
      get { return imageMaxSize_; }
      set {
        imageMaxSize_ = value;
      }
    }

    /// <summary>Field number for the "schrodinger_contract_address" field.</summary>
    public const int SchrodingerContractAddressFieldNumber = 3;
    private global::AElf.Types.Address schrodingerContractAddress_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AElf.Types.Address SchrodingerContractAddress {
      get { return schrodingerContractAddress_; }
      set {
        schrodingerContractAddress_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as InitializeInput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(InitializeInput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Admin, other.Admin)) return false;
      if (ImageMaxSize != other.ImageMaxSize) return false;
      if (!object.Equals(SchrodingerContractAddress, other.SchrodingerContractAddress)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (admin_ != null) hash ^= Admin.GetHashCode();
      if (ImageMaxSize != 0L) hash ^= ImageMaxSize.GetHashCode();
      if (schrodingerContractAddress_ != null) hash ^= SchrodingerContractAddress.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (admin_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Admin);
      }
      if (ImageMaxSize != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ImageMaxSize);
      }
      if (schrodingerContractAddress_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(SchrodingerContractAddress);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (admin_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Admin);
      }
      if (ImageMaxSize != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ImageMaxSize);
      }
      if (schrodingerContractAddress_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(SchrodingerContractAddress);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (admin_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Admin);
      }
      if (ImageMaxSize != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ImageMaxSize);
      }
      if (schrodingerContractAddress_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SchrodingerContractAddress);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(InitializeInput other) {
      if (other == null) {
        return;
      }
      if (other.admin_ != null) {
        if (admin_ == null) {
          Admin = new global::AElf.Types.Address();
        }
        Admin.MergeFrom(other.Admin);
      }
      if (other.ImageMaxSize != 0L) {
        ImageMaxSize = other.ImageMaxSize;
      }
      if (other.schrodingerContractAddress_ != null) {
        if (schrodingerContractAddress_ == null) {
          SchrodingerContractAddress = new global::AElf.Types.Address();
        }
        SchrodingerContractAddress.MergeFrom(other.SchrodingerContractAddress);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (admin_ == null) {
              Admin = new global::AElf.Types.Address();
            }
            input.ReadMessage(Admin);
            break;
          }
          case 16: {
            ImageMaxSize = input.ReadInt64();
            break;
          }
          case 26: {
            if (schrodingerContractAddress_ == null) {
              SchrodingerContractAddress = new global::AElf.Types.Address();
            }
            input.ReadMessage(SchrodingerContractAddress);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (admin_ == null) {
              Admin = new global::AElf.Types.Address();
            }
            input.ReadMessage(Admin);
            break;
          }
          case 16: {
            ImageMaxSize = input.ReadInt64();
            break;
          }
          case 26: {
            if (schrodingerContractAddress_ == null) {
              SchrodingerContractAddress = new global::AElf.Types.Address();
            }
            input.ReadMessage(SchrodingerContractAddress);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class DeployInput : pb::IMessage<DeployInput>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DeployInput> _parser = new pb::MessageParser<DeployInput>(() => new DeployInput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DeployInput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SchrodingerMain.SchrodingerContractMainReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeployInput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeployInput(DeployInput other) : this() {
      tick_ = other.tick_;
      image_ = other.image_;
      seedSymbol_ = other.seedSymbol_;
      tokenName_ = other.tokenName_;
      decimals_ = other.decimals_;
      issueChainId_ = other.issueChainId_;
      imageUri_ = other.imageUri_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeployInput Clone() {
      return new DeployInput(this);
    }

    /// <summary>Field number for the "tick" field.</summary>
    public const int TickFieldNumber = 1;
    private string tick_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Tick {
      get { return tick_; }
      set {
        tick_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "image" field.</summary>
    public const int ImageFieldNumber = 2;
    private string image_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Image {
      get { return image_; }
      set {
        image_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "seed_symbol" field.</summary>
    public const int SeedSymbolFieldNumber = 3;
    private string seedSymbol_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SeedSymbol {
      get { return seedSymbol_; }
      set {
        seedSymbol_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "token_name" field.</summary>
    public const int TokenNameFieldNumber = 4;
    private string tokenName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TokenName {
      get { return tokenName_; }
      set {
        tokenName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "decimals" field.</summary>
    public const int DecimalsFieldNumber = 5;
    private int decimals_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Decimals {
      get { return decimals_; }
      set {
        decimals_ = value;
      }
    }

    /// <summary>Field number for the "issue_chain_id" field.</summary>
    public const int IssueChainIdFieldNumber = 6;
    private int issueChainId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int IssueChainId {
      get { return issueChainId_; }
      set {
        issueChainId_ = value;
      }
    }

    /// <summary>Field number for the "image_uri" field.</summary>
    public const int ImageUriFieldNumber = 7;
    private string imageUri_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ImageUri {
      get { return imageUri_; }
      set {
        imageUri_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DeployInput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DeployInput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Tick != other.Tick) return false;
      if (Image != other.Image) return false;
      if (SeedSymbol != other.SeedSymbol) return false;
      if (TokenName != other.TokenName) return false;
      if (Decimals != other.Decimals) return false;
      if (IssueChainId != other.IssueChainId) return false;
      if (ImageUri != other.ImageUri) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Tick.Length != 0) hash ^= Tick.GetHashCode();
      if (Image.Length != 0) hash ^= Image.GetHashCode();
      if (SeedSymbol.Length != 0) hash ^= SeedSymbol.GetHashCode();
      if (TokenName.Length != 0) hash ^= TokenName.GetHashCode();
      if (Decimals != 0) hash ^= Decimals.GetHashCode();
      if (IssueChainId != 0) hash ^= IssueChainId.GetHashCode();
      if (ImageUri.Length != 0) hash ^= ImageUri.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Tick.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Tick);
      }
      if (Image.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Image);
      }
      if (SeedSymbol.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(SeedSymbol);
      }
      if (TokenName.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(TokenName);
      }
      if (Decimals != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Decimals);
      }
      if (IssueChainId != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(IssueChainId);
      }
      if (ImageUri.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(ImageUri);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Tick.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Tick);
      }
      if (Image.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Image);
      }
      if (SeedSymbol.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(SeedSymbol);
      }
      if (TokenName.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(TokenName);
      }
      if (Decimals != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Decimals);
      }
      if (IssueChainId != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(IssueChainId);
      }
      if (ImageUri.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(ImageUri);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Tick.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Tick);
      }
      if (Image.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Image);
      }
      if (SeedSymbol.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SeedSymbol);
      }
      if (TokenName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TokenName);
      }
      if (Decimals != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Decimals);
      }
      if (IssueChainId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IssueChainId);
      }
      if (ImageUri.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ImageUri);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DeployInput other) {
      if (other == null) {
        return;
      }
      if (other.Tick.Length != 0) {
        Tick = other.Tick;
      }
      if (other.Image.Length != 0) {
        Image = other.Image;
      }
      if (other.SeedSymbol.Length != 0) {
        SeedSymbol = other.SeedSymbol;
      }
      if (other.TokenName.Length != 0) {
        TokenName = other.TokenName;
      }
      if (other.Decimals != 0) {
        Decimals = other.Decimals;
      }
      if (other.IssueChainId != 0) {
        IssueChainId = other.IssueChainId;
      }
      if (other.ImageUri.Length != 0) {
        ImageUri = other.ImageUri;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Tick = input.ReadString();
            break;
          }
          case 18: {
            Image = input.ReadString();
            break;
          }
          case 26: {
            SeedSymbol = input.ReadString();
            break;
          }
          case 34: {
            TokenName = input.ReadString();
            break;
          }
          case 40: {
            Decimals = input.ReadInt32();
            break;
          }
          case 48: {
            IssueChainId = input.ReadInt32();
            break;
          }
          case 58: {
            ImageUri = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Tick = input.ReadString();
            break;
          }
          case 18: {
            Image = input.ReadString();
            break;
          }
          case 26: {
            SeedSymbol = input.ReadString();
            break;
          }
          case 34: {
            TokenName = input.ReadString();
            break;
          }
          case 40: {
            Decimals = input.ReadInt32();
            break;
          }
          case 48: {
            IssueChainId = input.ReadInt32();
            break;
          }
          case 58: {
            ImageUri = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ExternalInfos : pb::IMessage<ExternalInfos>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ExternalInfos> _parser = new pb::MessageParser<ExternalInfos>(() => new ExternalInfos());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ExternalInfos> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SchrodingerMain.SchrodingerContractMainReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExternalInfos() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExternalInfos(ExternalInfos other) : this() {
      value_ = other.value_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExternalInfos Clone() {
      return new ExternalInfos(this);
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 1;
    private static readonly pbc::MapField<string, string>.Codec _map_value_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 10);
    private readonly pbc::MapField<string, string> value_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, string> Value {
      get { return value_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ExternalInfos);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ExternalInfos other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!Value.Equals(other.Value)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= Value.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      value_.WriteTo(output, _map_value_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      value_.WriteTo(ref output, _map_value_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += value_.CalculateSize(_map_value_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ExternalInfos other) {
      if (other == null) {
        return;
      }
      value_.Add(other.value_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            value_.AddEntriesFrom(input, _map_value_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            value_.AddEntriesFrom(ref input, _map_value_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class DeployInscriptionInfo : pb::IMessage<DeployInscriptionInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DeployInscriptionInfo> _parser = new pb::MessageParser<DeployInscriptionInfo>(() => new DeployInscriptionInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DeployInscriptionInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SchrodingerMain.SchrodingerContractMainReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeployInscriptionInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeployInscriptionInfo(DeployInscriptionInfo other) : this() {
      p_ = other.p_;
      op_ = other.op_;
      tick_ = other.tick_;
      max_ = other.max_;
      lim_ = other.lim_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeployInscriptionInfo Clone() {
      return new DeployInscriptionInfo(this);
    }

    /// <summary>Field number for the "p" field.</summary>
    public const int PFieldNumber = 1;
    private string p_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string P {
      get { return p_; }
      set {
        p_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "op" field.</summary>
    public const int OpFieldNumber = 2;
    private string op_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Op {
      get { return op_; }
      set {
        op_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tick" field.</summary>
    public const int TickFieldNumber = 3;
    private string tick_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Tick {
      get { return tick_; }
      set {
        tick_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "max" field.</summary>
    public const int MaxFieldNumber = 4;
    private string max_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Max {
      get { return max_; }
      set {
        max_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "lim" field.</summary>
    public const int LimFieldNumber = 5;
    private string lim_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Lim {
      get { return lim_; }
      set {
        lim_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DeployInscriptionInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DeployInscriptionInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (P != other.P) return false;
      if (Op != other.Op) return false;
      if (Tick != other.Tick) return false;
      if (Max != other.Max) return false;
      if (Lim != other.Lim) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (P.Length != 0) hash ^= P.GetHashCode();
      if (Op.Length != 0) hash ^= Op.GetHashCode();
      if (Tick.Length != 0) hash ^= Tick.GetHashCode();
      if (Max.Length != 0) hash ^= Max.GetHashCode();
      if (Lim.Length != 0) hash ^= Lim.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (P.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(P);
      }
      if (Op.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Op);
      }
      if (Tick.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Tick);
      }
      if (Max.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Max);
      }
      if (Lim.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Lim);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (P.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(P);
      }
      if (Op.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Op);
      }
      if (Tick.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Tick);
      }
      if (Max.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Max);
      }
      if (Lim.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Lim);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (P.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(P);
      }
      if (Op.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Op);
      }
      if (Tick.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Tick);
      }
      if (Max.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Max);
      }
      if (Lim.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Lim);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DeployInscriptionInfo other) {
      if (other == null) {
        return;
      }
      if (other.P.Length != 0) {
        P = other.P;
      }
      if (other.Op.Length != 0) {
        Op = other.Op;
      }
      if (other.Tick.Length != 0) {
        Tick = other.Tick;
      }
      if (other.Max.Length != 0) {
        Max = other.Max;
      }
      if (other.Lim.Length != 0) {
        Lim = other.Lim;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            P = input.ReadString();
            break;
          }
          case 18: {
            Op = input.ReadString();
            break;
          }
          case 26: {
            Tick = input.ReadString();
            break;
          }
          case 34: {
            Max = input.ReadString();
            break;
          }
          case 42: {
            Lim = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            P = input.ReadString();
            break;
          }
          case 18: {
            Op = input.ReadString();
            break;
          }
          case 26: {
            Tick = input.ReadString();
            break;
          }
          case 34: {
            Max = input.ReadString();
            break;
          }
          case 42: {
            Lim = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// log event
  /// </summary>
  public sealed partial class CollectionDeployed : pb::IMessage<CollectionDeployed>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CollectionDeployed> _parser = new pb::MessageParser<CollectionDeployed>(() => new CollectionDeployed());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CollectionDeployed> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SchrodingerMain.SchrodingerContractMainReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CollectionDeployed() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CollectionDeployed(CollectionDeployed other) : this() {
      symbol_ = other.symbol_;
      totalSupply_ = other.totalSupply_;
      issuer_ = other.issuer_ != null ? other.issuer_.Clone() : null;
      owner_ = other.owner_ != null ? other.owner_.Clone() : null;
      issueChainId_ = other.issueChainId_;
      collectionExternalInfos_ = other.collectionExternalInfos_ != null ? other.collectionExternalInfos_.Clone() : null;
      deployer_ = other.deployer_ != null ? other.deployer_.Clone() : null;
      tokenName_ = other.tokenName_;
      decimals_ = other.decimals_;
      imageUri_ = other.imageUri_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CollectionDeployed Clone() {
      return new CollectionDeployed(this);
    }

    /// <summary>Field number for the "symbol" field.</summary>
    public const int SymbolFieldNumber = 1;
    private string symbol_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Symbol {
      get { return symbol_; }
      set {
        symbol_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "total_supply" field.</summary>
    public const int TotalSupplyFieldNumber = 2;
    private long totalSupply_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TotalSupply {
      get { return totalSupply_; }
      set {
        totalSupply_ = value;
      }
    }

    /// <summary>Field number for the "issuer" field.</summary>
    public const int IssuerFieldNumber = 3;
    private global::AElf.Types.Address issuer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AElf.Types.Address Issuer {
      get { return issuer_; }
      set {
        issuer_ = value;
      }
    }

    /// <summary>Field number for the "owner" field.</summary>
    public const int OwnerFieldNumber = 4;
    private global::AElf.Types.Address owner_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AElf.Types.Address Owner {
      get { return owner_; }
      set {
        owner_ = value;
      }
    }

    /// <summary>Field number for the "issue_chain_id" field.</summary>
    public const int IssueChainIdFieldNumber = 5;
    private int issueChainId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int IssueChainId {
      get { return issueChainId_; }
      set {
        issueChainId_ = value;
      }
    }

    /// <summary>Field number for the "collection_external_infos" field.</summary>
    public const int CollectionExternalInfosFieldNumber = 6;
    private global::SchrodingerMain.ExternalInfos collectionExternalInfos_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SchrodingerMain.ExternalInfos CollectionExternalInfos {
      get { return collectionExternalInfos_; }
      set {
        collectionExternalInfos_ = value;
      }
    }

    /// <summary>Field number for the "deployer" field.</summary>
    public const int DeployerFieldNumber = 7;
    private global::AElf.Types.Address deployer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AElf.Types.Address Deployer {
      get { return deployer_; }
      set {
        deployer_ = value;
      }
    }

    /// <summary>Field number for the "token_name" field.</summary>
    public const int TokenNameFieldNumber = 8;
    private string tokenName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TokenName {
      get { return tokenName_; }
      set {
        tokenName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "decimals" field.</summary>
    public const int DecimalsFieldNumber = 9;
    private int decimals_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Decimals {
      get { return decimals_; }
      set {
        decimals_ = value;
      }
    }

    /// <summary>Field number for the "image_uri" field.</summary>
    public const int ImageUriFieldNumber = 10;
    private string imageUri_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ImageUri {
      get { return imageUri_; }
      set {
        imageUri_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CollectionDeployed);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CollectionDeployed other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Symbol != other.Symbol) return false;
      if (TotalSupply != other.TotalSupply) return false;
      if (!object.Equals(Issuer, other.Issuer)) return false;
      if (!object.Equals(Owner, other.Owner)) return false;
      if (IssueChainId != other.IssueChainId) return false;
      if (!object.Equals(CollectionExternalInfos, other.CollectionExternalInfos)) return false;
      if (!object.Equals(Deployer, other.Deployer)) return false;
      if (TokenName != other.TokenName) return false;
      if (Decimals != other.Decimals) return false;
      if (ImageUri != other.ImageUri) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Symbol.Length != 0) hash ^= Symbol.GetHashCode();
      if (TotalSupply != 0L) hash ^= TotalSupply.GetHashCode();
      if (issuer_ != null) hash ^= Issuer.GetHashCode();
      if (owner_ != null) hash ^= Owner.GetHashCode();
      if (IssueChainId != 0) hash ^= IssueChainId.GetHashCode();
      if (collectionExternalInfos_ != null) hash ^= CollectionExternalInfos.GetHashCode();
      if (deployer_ != null) hash ^= Deployer.GetHashCode();
      if (TokenName.Length != 0) hash ^= TokenName.GetHashCode();
      if (Decimals != 0) hash ^= Decimals.GetHashCode();
      if (ImageUri.Length != 0) hash ^= ImageUri.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Symbol.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Symbol);
      }
      if (TotalSupply != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(TotalSupply);
      }
      if (issuer_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Issuer);
      }
      if (owner_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Owner);
      }
      if (IssueChainId != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(IssueChainId);
      }
      if (collectionExternalInfos_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(CollectionExternalInfos);
      }
      if (deployer_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Deployer);
      }
      if (TokenName.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(TokenName);
      }
      if (Decimals != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(Decimals);
      }
      if (ImageUri.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(ImageUri);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Symbol.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Symbol);
      }
      if (TotalSupply != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(TotalSupply);
      }
      if (issuer_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Issuer);
      }
      if (owner_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Owner);
      }
      if (IssueChainId != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(IssueChainId);
      }
      if (collectionExternalInfos_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(CollectionExternalInfos);
      }
      if (deployer_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Deployer);
      }
      if (TokenName.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(TokenName);
      }
      if (Decimals != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(Decimals);
      }
      if (ImageUri.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(ImageUri);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Symbol.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Symbol);
      }
      if (TotalSupply != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TotalSupply);
      }
      if (issuer_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Issuer);
      }
      if (owner_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Owner);
      }
      if (IssueChainId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IssueChainId);
      }
      if (collectionExternalInfos_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CollectionExternalInfos);
      }
      if (deployer_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Deployer);
      }
      if (TokenName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TokenName);
      }
      if (Decimals != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Decimals);
      }
      if (ImageUri.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ImageUri);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CollectionDeployed other) {
      if (other == null) {
        return;
      }
      if (other.Symbol.Length != 0) {
        Symbol = other.Symbol;
      }
      if (other.TotalSupply != 0L) {
        TotalSupply = other.TotalSupply;
      }
      if (other.issuer_ != null) {
        if (issuer_ == null) {
          Issuer = new global::AElf.Types.Address();
        }
        Issuer.MergeFrom(other.Issuer);
      }
      if (other.owner_ != null) {
        if (owner_ == null) {
          Owner = new global::AElf.Types.Address();
        }
        Owner.MergeFrom(other.Owner);
      }
      if (other.IssueChainId != 0) {
        IssueChainId = other.IssueChainId;
      }
      if (other.collectionExternalInfos_ != null) {
        if (collectionExternalInfos_ == null) {
          CollectionExternalInfos = new global::SchrodingerMain.ExternalInfos();
        }
        CollectionExternalInfos.MergeFrom(other.CollectionExternalInfos);
      }
      if (other.deployer_ != null) {
        if (deployer_ == null) {
          Deployer = new global::AElf.Types.Address();
        }
        Deployer.MergeFrom(other.Deployer);
      }
      if (other.TokenName.Length != 0) {
        TokenName = other.TokenName;
      }
      if (other.Decimals != 0) {
        Decimals = other.Decimals;
      }
      if (other.ImageUri.Length != 0) {
        ImageUri = other.ImageUri;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Symbol = input.ReadString();
            break;
          }
          case 16: {
            TotalSupply = input.ReadInt64();
            break;
          }
          case 26: {
            if (issuer_ == null) {
              Issuer = new global::AElf.Types.Address();
            }
            input.ReadMessage(Issuer);
            break;
          }
          case 34: {
            if (owner_ == null) {
              Owner = new global::AElf.Types.Address();
            }
            input.ReadMessage(Owner);
            break;
          }
          case 40: {
            IssueChainId = input.ReadInt32();
            break;
          }
          case 50: {
            if (collectionExternalInfos_ == null) {
              CollectionExternalInfos = new global::SchrodingerMain.ExternalInfos();
            }
            input.ReadMessage(CollectionExternalInfos);
            break;
          }
          case 58: {
            if (deployer_ == null) {
              Deployer = new global::AElf.Types.Address();
            }
            input.ReadMessage(Deployer);
            break;
          }
          case 66: {
            TokenName = input.ReadString();
            break;
          }
          case 72: {
            Decimals = input.ReadInt32();
            break;
          }
          case 82: {
            ImageUri = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Symbol = input.ReadString();
            break;
          }
          case 16: {
            TotalSupply = input.ReadInt64();
            break;
          }
          case 26: {
            if (issuer_ == null) {
              Issuer = new global::AElf.Types.Address();
            }
            input.ReadMessage(Issuer);
            break;
          }
          case 34: {
            if (owner_ == null) {
              Owner = new global::AElf.Types.Address();
            }
            input.ReadMessage(Owner);
            break;
          }
          case 40: {
            IssueChainId = input.ReadInt32();
            break;
          }
          case 50: {
            if (collectionExternalInfos_ == null) {
              CollectionExternalInfos = new global::SchrodingerMain.ExternalInfos();
            }
            input.ReadMessage(CollectionExternalInfos);
            break;
          }
          case 58: {
            if (deployer_ == null) {
              Deployer = new global::AElf.Types.Address();
            }
            input.ReadMessage(Deployer);
            break;
          }
          case 66: {
            TokenName = input.ReadString();
            break;
          }
          case 72: {
            Decimals = input.ReadInt32();
            break;
          }
          case 82: {
            ImageUri = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
